local _, KWR = ...

-- Generated by tools/compile-season2-rbg-lifecycle.ps1. Do not edit.
-- Only independently reviewed, observed, unexpired records may appear here.
local Season2CorpusLifecycle = {
    schemaVersion = 1,
    sourceStatus = "SIMULATION_ONLY",
    promotedCount = 0,
    promoted = {
    },
}

function Season2CorpusLifecycle:Count() return self.promotedCount end
function Season2CorpusLifecycle:Get(caseId) return self.promoted[caseId] end
function Season2CorpusLifecycle:Shared() return self end

KWR.Season2CorpusLifecycle = Season2CorpusLifecycle
KWR:RegisterModule("Season2CorpusLifecycle", Season2CorpusLifecycle)
