[CmdletBinding()]
param(
    [string]$InputFile = "knowledge\season2-rbg-simulation-corpus.json",
    [string]$OutputFile = "Data\StrategistNexusCorpus.lua"
)

$ErrorActionPreference = "Stop"
$root = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$inputPath = if ([IO.Path]::IsPathRooted($InputFile)) {
    [IO.Path]::GetFullPath($InputFile)
} else { Join-Path $root $InputFile }
$outputPath = if ([IO.Path]::IsPathRooted($OutputFile)) {
    [IO.Path]::GetFullPath($OutputFile)
} else { Join-Path $root $OutputFile }
$document = Get-Content -LiteralPath $inputPath -Raw | ConvertFrom-Json
$cases = @($document.cases)

if ($document.schema -ne "kwr-season2-rbg-simulation-corpus") {
    throw "Unexpected Strategist Nexus corpus schema: $($document.schema)"
}
if ([int]$document.totalCases -ne 5000 -or $cases.Count -ne 5000) {
    throw "Strategist Nexus requires exactly 5,000 source cases."
}
if (@($cases.caseId | Sort-Object -Unique).Count -ne $cases.Count) {
    throw "Strategist Nexus source case IDs are not unique."
}
if (@($cases.contentHash | Sort-Object -Unique).Count -ne $cases.Count) {
    throw "Strategist Nexus source content hashes are not unique."
}
if (@($cases | Where-Object status -ne "SIMULATION_ONLY").Count -gt 0) {
    throw "The offline Nexus compiler only accepts SIMULATION_ONLY cases."
}

function ConvertTo-LuaString {
    param([AllowNull()][object]$Value)
    $text = [string]$Value
    $text = $text.Replace('\', '\\').Replace('"', '\"')
    $text = $text.Replace("`r", '\r').Replace("`n", '\n')
    return '"' + $text + '"'
}

function Add-Count {
    param(
        [Parameter(Mandatory = $true)][hashtable]$Table,
        [Parameter(Mandatory = $true)][string]$Key
    )
    $current = if ($Table.ContainsKey($Key)) { [int]$Table[$Key] } else { 0 }
    $Table[$Key] = $current + 1
}

function Write-CountTable {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [Parameter(Mandatory = $true)][string]$Indent,
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][hashtable]$Values
    )
    $Lines.Add("$Indent$Name = {")
    foreach ($key in @($Values.Keys | Sort-Object)) {
        $Lines.Add("$Indent    [$(ConvertTo-LuaString $key)] = $($Values[$key]),")
    }
    $Lines.Add("$Indent},")
}

$maps = @{}
foreach ($case in $cases) {
    $mapKey = [string]$case.mapKey
    $phase = [string]$case.phase
    if (-not $maps.ContainsKey($mapKey)) {
        $maps[$mapKey] = @{
            mapProfile = [string]$case.mapProfile
            totalCases = 0
            phases = @{}
        }
    }
    $map = $maps[$mapKey]
    $map.totalCases++
    if (-not $map.phases.ContainsKey($phase)) {
        $map.phases[$phase] = @{
            totalCases = 0
            families = @{}
            compWatches = @{}
            scoreStates = @{}
            counterResponses = @{}
            evidenceStates = @{}
            outcomeBranches = @{}
            sourceScenarios = @{}
        }
    }
    $bucket = $map.phases[$phase]
    $bucket.totalCases++
    Add-Count $bucket.families ([string]$case.scenarioFamily)
    Add-Count $bucket.compWatches ([string]$case.compWatch)
    Add-Count $bucket.scoreStates ([string]$case.scoreState)
    Add-Count $bucket.counterResponses ([string]$case.counterResponse)
    Add-Count $bucket.evidenceStates ([string]$case.evidenceState)
    Add-Count $bucket.outcomeBranches ([string]$case.outcomeBranch)
    Add-Count $bucket.sourceScenarios ([string]$case.sourceScenarioId)
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('local _, KWR = ...')
$lines.Add('')
$lines.Add('-- Generated by tools/build-strategist-nexus-corpus.ps1. Do not edit.')
$lines.Add('-- Counts describe deterministic branch coverage, not empirical win rates.')
$lines.Add('local StrategistNexusCorpus = {}')
$lines.Add('KWR.StrategistNexusCorpus = StrategistNexusCorpus')
$lines.Add('')
$lines.Add('local DATA = {')
$lines.Add('    schemaVersion = 1,')
$lines.Add("    sourceSchemaVersion = $([int]$document.schemaVersion),")
$lines.Add("    patch = $(ConvertTo-LuaString $document.patch),")
$lines.Add("    sourceStatus = $(ConvertTo-LuaString $document.status),")
$lines.Add("    activation = $(ConvertTo-LuaString $document.activation),")
$lines.Add("    totalCases = $($cases.Count),")
$lines.Add('    maps = {')
foreach ($mapKey in @($maps.Keys | Sort-Object)) {
    $map = $maps[$mapKey]
    $lines.Add("        [$((ConvertTo-LuaString $mapKey))] = {")
    $lines.Add("            mapProfile = $(ConvertTo-LuaString $map.mapProfile),")
    $lines.Add("            totalCases = $($map.totalCases),")
    $lines.Add('            phases = {')
    foreach ($phase in @($map.phases.Keys | Sort-Object)) {
        $bucket = $map.phases[$phase]
        $lines.Add("                [$((ConvertTo-LuaString $phase))] = {")
        $lines.Add("                    totalCases = $($bucket.totalCases),")
        Write-CountTable $lines '                    ' 'families' $bucket.families
        Write-CountTable $lines '                    ' 'compWatches' $bucket.compWatches
        Write-CountTable $lines '                    ' 'scoreStates' $bucket.scoreStates
        Write-CountTable $lines '                    ' 'counterResponses' $bucket.counterResponses
        Write-CountTable $lines '                    ' 'evidenceStates' $bucket.evidenceStates
        Write-CountTable $lines '                    ' 'outcomeBranches' $bucket.outcomeBranches
        Write-CountTable $lines '                    ' 'sourceScenarios' $bucket.sourceScenarios
        $lines.Add('                },')
    }
    $lines.Add('            },')
    $lines.Add('        },')
}
$lines.Add('    },')
$lines.Add('}')
$lines.Add('')
$lines.Add('local function narrow(current, values, key)')
$lines.Add('    if not key then return current end')
$lines.Add('    local count = values and values[key] or 0')
$lines.Add('    return math.min(current, count)')
$lines.Add('end')
$lines.Add('')
$lines.Add('function StrategistNexusCorpus:Count() return DATA.totalCases end')
$lines.Add('function StrategistNexusCorpus:Status() return DATA.sourceStatus end')
$lines.Add('function StrategistNexusCorpus:Activation() return DATA.activation end')
$lines.Add('function StrategistNexusCorpus:Patch() return DATA.patch end')
$lines.Add('function StrategistNexusCorpus:Map(mapKey) return DATA.maps[mapKey] end')
$lines.Add('')
$lines.Add('function StrategistNexusCorpus:Coverage(mapKey, phase, query)')
$lines.Add('    local map = DATA.maps[mapKey]')
$lines.Add('    local bucket = map and map.phases and map.phases[phase]')
$lines.Add('    if not bucket then')
$lines.Add('        return { available = false, marginalCases = 0, sourceStatus = DATA.sourceStatus }')
$lines.Add('    end')
$lines.Add('    query = type(query) == "table" and query or {}')
$lines.Add('    local count = bucket.totalCases')
$lines.Add('    count = narrow(count, bucket.families, query.family)')
$lines.Add('    count = narrow(count, bucket.compWatches, query.compWatch)')
$lines.Add('    count = narrow(count, bucket.scoreStates, query.scoreState)')
$lines.Add('    count = narrow(count, bucket.counterResponses, query.counterResponse)')
$lines.Add('    count = narrow(count, bucket.evidenceStates, query.evidenceState)')
$lines.Add('    return {')
$lines.Add('        available = count > 0,')
$lines.Add('        marginalCases = count,')
$lines.Add('        phaseCases = bucket.totalCases,')
$lines.Add('        mapCases = map.totalCases,')
$lines.Add('        totalCases = DATA.totalCases,')
$lines.Add('        sourceStatus = DATA.sourceStatus,')
$lines.Add('        patch = DATA.patch,')
$lines.Add('        mapProfile = map.mapProfile,')
$lines.Add('    }')
$lines.Add('end')
$lines.Add('')
$lines.Add('function StrategistNexusCorpus:Shared() return DATA end')
$lines.Add('')
$lines.Add('KWR:RegisterModule("StrategistNexusCorpus", StrategistNexusCorpus)')

[IO.File]::WriteAllText($outputPath, (($lines -join "`n") + "`n"),
    [Text.UTF8Encoding]::new($false))
Write-Output "Strategist Nexus corpus: $($cases.Count) cases -> $OutputFile"
