[CmdletBinding()]
param(
    [string]$CorpusFile = "knowledge\season2-rbg-simulation-corpus.json",
    [string]$OutFile = "Data\Season2CorpusLifecycle.lua",
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$root = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$corpusPath = Join-Path $root $CorpusFile
$outPath = Join-Path $root $OutFile
$corpus = Get-Content -LiteralPath $corpusPath -Raw | ConvertFrom-Json
$errors = [System.Collections.Generic.List[string]]::new()
$eligible = [System.Collections.Generic.List[object]]::new()

foreach ($case in @($corpus.cases)) {
    $status = [string]$case.status
    if ($status -eq 'PROMOTED') {
        # Promotion is intentionally impossible from an offline simulation
        # alone. These facts are required before any compact runtime row exists.
        $required = @('reviewers', 'liveAarIds', 'replayPassed', 'adversarialPassed', 'calibrationPassed', 'expiresAt')
        foreach ($field in $required) {
            if ($null -eq $case.PSObject.Properties[$field]) {
                $errors.Add("Promoted case $($case.caseId) is missing $field.")
            }
        }
        if (@($case.reviewers).Count -lt 2 -or @($case.liveAarIds).Count -lt 3 -or
            $case.replayPassed -ne $true -or $case.adversarialPassed -ne $true -or
            $case.calibrationPassed -ne $true) {
            $errors.Add("Promoted case $($case.caseId) does not satisfy review, live-AAR, and regression gates.")
        }
        $expiry = $null
        if (-not [DateTimeOffset]::TryParse([string]$case.expiresAt, [ref]$expiry) -or $expiry -le [DateTimeOffset]::UtcNow) {
            $errors.Add("Promoted case $($case.caseId) has no future expiry.")
        }
        if ($case.source -eq 'SEASON_2_PRE_LIVE_DETERMINISTIC') {
            $errors.Add("Simulation-only case $($case.caseId) may never be promoted in place.")
        }
        if ($errors.Count -eq 0) {
            $eligible.Add([ordered]@{
                caseId = [string]$case.caseId
                mapKey = [string]$case.mapKey
                phase = [string]$case.phase
                sourceScenarioId = [string]$case.sourceScenarioId
                contentHash = [string]$case.contentHash
                expiresAt = [string]$case.expiresAt
            }) | Out-Null
        }
    } elseif ($status -notin @('SIMULATION_ONLY', 'DOCTRINE_REVIEWED', 'FIELD_OBSERVED', 'QUARANTINED', 'RETIRED')) {
        $errors.Add("Case $($case.caseId) has an unknown lifecycle status: $status")
    }
}

if ($errors.Count -gt 0) {
    $errors | ForEach-Object { Write-Error $_ -ErrorAction Continue }
    exit 1
}

$rows = @($eligible | Sort-Object caseId | ForEach-Object {
    ('    ["{0}"] = {{ mapKey = "{1}", phase = "{2}", scenarioId = "{3}", hash = "{4}", expiresAt = "{5}" }},' -f
        $_.caseId, $_.mapKey, $_.phase, $_.sourceScenarioId, $_.contentHash, $_.expiresAt)
})
$luaLines = [System.Collections.Generic.List[string]]::new()
foreach ($line in @(
    'local _, KWR = ...',
    '',
    '-- Generated by tools/compile-season2-rbg-lifecycle.ps1. Do not edit.',
    '-- Only independently reviewed, observed, unexpired records may appear here.',
    'local Season2CorpusLifecycle = {',
    '    schemaVersion = 1,',
    ('    sourceStatus = "{0}",' -f $corpus.status),
    ('    promotedCount = {0},' -f $eligible.Count),
    '    promoted = {'
)) { $luaLines.Add([string]$line) | Out-Null }
foreach ($row in $rows) { $luaLines.Add([string]$row) | Out-Null }
foreach ($line in @(
    '    },',
    '}',
    '',
    'function Season2CorpusLifecycle:Count() return self.promotedCount end',
    'function Season2CorpusLifecycle:Get(caseId) return self.promoted[caseId] end',
    'function Season2CorpusLifecycle:Shared() return self end',
    '',
    'KWR.Season2CorpusLifecycle = Season2CorpusLifecycle',
    'KWR:RegisterModule("Season2CorpusLifecycle", Season2CorpusLifecycle)',
    ''
)) { $luaLines.Add([string]$line) | Out-Null }
$lua = $luaLines -join "`n"

if ($Check) {
    if (-not (Test-Path -LiteralPath $outPath) -or (Get-Content -LiteralPath $outPath -Raw) -cne $lua) {
        Write-Error "Season 2 lifecycle runtime data is missing or stale. Run compile-season2-rbg-lifecycle.ps1."
        exit 1
    }
} else {
    [IO.File]::WriteAllText($outPath, $lua, [Text.UTF8Encoding]::new($false))
}

Write-Output "KWR Season 2 lifecycle compile PASS promoted=$($eligible.Count) mode=$(if ($Check) { 'check' } else { 'write' })"
